### ISSUE TITLE
Release as npm package

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/perf-goggles#1]
By doing so we will be able to use on projects like firefox-health-dashboard (a forked version is landed there), the js-perf-dashboard and the perf-goggles-demo.

@csd713 is interested on working on this.

**Comment by ghost** [comment]
I wanted to confirm about the actions to be taken.

1. Fork and Clone [mozilla-frontend-infra/perf-goggles](https://github.com/mozilla-frontend-infra/perf-goggles) repo locally
2. For the same repo use nutrino wizard and and select library preset
3. (This is where I'm confused) Should I copy the code from [old](https://github.com/mozilla-frontend-infra/perf-goggles-demo) repo? or what's the next step?

**Comment by armenzg** [comment]
You got the gist of it!

The only code to be copied from the other repo is src/utils/perfherder.js

For the wizard all you have to do is follow the instructions on [this page](https://neutrinojs.org/installation/create-new-project.html).

**Comment by ghost** [comment]
Hi @armenzg 
I created a PR #2 for this issue.
I'm unsure of next steps. Please review the same and let me know if I'm on right track.
